services:
  bridge:
    platform: linux/arm64
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    volumes:
      - /opt/gst-plugins-rs:/opt/gst-plugins-rs:ro
    environment:
      - GST_PLUGIN_PATH=/opt/gst-plugins-rs/lib/aarch64-linux-gnu
